package com.zagyvaib.example.spring.data.jpa.layering.infrastructure;

import org.springframework.data.jpa.repository.JpaRepository;

import java.io.Serializable;

/**
 * Intermediate interface that declares the shared behaviour of all repository interfaces. Individual repository
 * interfaces should extend this one instead of the {@link org.springframework.data.jpa.repository.JpaRepository}
 * interface.
 * <p>
 * There is no actual functionality declared on this interface, because we only want to change the transactional
 * attributes associated with the repository implementations generated by the infrastructure. This can be achieved by
 * properly annotating the implementation of this interface ({@link ExistingTransactionDemandingRepositoryImpl}).
 * <p>
 * Implemented according to section
 * <a href="http://static.springsource.org/spring-data/data-jpa/docs/1.3.0.RELEASE/reference/html/repositories.html#repositories.custom-behaviour-for-all-repositories">
 * "Adding custom behaviour to all repositories"</a> in the Spring Data JPA reference documentation.
 */
public interface ExistingTransactionDemandingRepository<T, ID extends Serializable> extends JpaRepository<T, ID> {
}