package com.zagyvaib.example.spring.data.jpa.basic.repository;


import com.zagyvaib.example.spring.data.jpa.common.entity.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

// In conjunction with the <jpa:repositories> configuration element, the @Repository annotation causes the exception
// translation advice to be applied on the implementation generated by the infrastructure for the repository that is
// specified by this interface.
@Repository
public interface EmployeeRepository extends JpaRepository<Employee, Long> {

    Employee findByName(String name);
}